#!/bin/bash
set -eu

if [[ ! -e "$PGDATA/db_configured" ]]; then
  init_db () {
    echo "Configuring CKAN database and PostGIS & datastore"

    # Create a user that has CREATEDB permissions.
    # This user will be used in the different Strabon containers to create their own databases
    setuser postgres psql \
      -c "CREATE USER $DBCREATE_USER WITH PASSWORD '$DBCREATE_PASS';"

    setuser postgres psql \
      -c "ALTER USER $DBCREATE_USER CREATEDB CREATEROLE;"

    setuser  postgres createdb -O $DBCREATE_USER $DBCREATE_DB


    # Create a POSTGIS template (for further use in Strabon)
    POSTGIS_SQL_PATH=`pg_config --sharedir`/contrib/postgis-2.1
    setuser postgres createdb -E UTF8 -T template0 template_postgis
    # setuser postgres createlang -d template_postgis plpgsql
    setuser postgres psql -d template_postgis -f /usr/share/pgsql/contrib/postgis-64.sql
    setuser postgres psql -d template_postgis -f /usr/share/pgsql/contrib/postgis-2.0/spatial_ref_sys.sql
    #setuser postgres psql -d template_postgis -f /usr/share/pgsql/contrib/postgis-2.0/postgis_comments.sql

    setuser postgres psql -d template_postgis -c "GRANT ALL ON geometry_columns TO PUBLIC;"
    setuser postgres psql -d template_postgis -c "GRANT ALL ON geography_columns TO PUBLIC;"
    setuser postgres psql -d template_postgis -c "GRANT ALL ON spatial_ref_sys TO PUBLIC;"

    setuser postgres psql -d template_postgis -c "VACUUM FULL;"
    setuser postgres psql -d template_postgis -c "VACUUM FREEZE;"

    setuser postgres psql -d postgres -c "UPDATE pg_database SET datistemplate='true' WHERE datname='template_postgis';"
    setuser postgres psql -d postgres -c "UPDATE pg_database SET datallowconn='false' WHERE datname='template_postgis';"



    # create CKAN user
    setuser postgres psql \
      -c "CREATE USER $CKAN_USER WITH PASSWORD '$CKAN_PASS';"

    # create CKAN database
    setuser postgres createdb \
      -O $CKAN_USER $CKAN_DB -T template_postgis -E utf-8

    # # setup PostGIS for the database
    # setuser postgres psql \
    #   -d $CKAN_DB -f /usr/share/pgsql/contrib/postgis-64.sql
    #   #-d $CKAN_DB -f /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis.sql
    #
    # setuser postgres psql \
    #   -d $CKAN_DB -f /usr/share/pgsql/contrib/postgis-2.0/spatial_ref_sys.sql
    #   #-d $CKAN_DB -f /usr/share/postgresql/9.3/contrib/postgis-2.1/spatial_ref_sys.sql
    #
    # setuser postgres psql \
    #   -d $CKAN_DB -f /usr/share/pgsql/contrib/postgis-2.0/postgis_comments.sql
    #   #d $CKAN_DB -f /usr/share/postgresql/9.3/contrib/postgis-2.1/postgis_comments.sql
    # # change the ownership of the spatial tables
    setuser postgres psql \
      -d $CKAN_DB -c "ALTER TABLE spatial_ref_sys OWNER TO $CKAN_USER;"
    setuser postgres psql \
      -d $CKAN_DB -c "ALTER TABLE geometry_columns OWNER TO $CKAN_USER;"

    # create Datastore user
    setuser postgres psql \
      -c "CREATE USER $DATASTORE_USER WITH PASSWORD '$DATASTORE_PASS';"
    # create Datastore database
    setuser postgres createdb \
      -O $CKAN_USER $DATASTORE_DB -T template0  -E utf-8

    # configure the permissions for the datastore
    setuser postgres psql \
      -q <<-EOF
    \connect $DATASTORE_DB

    -- revoke permissions for the read-only user
    REVOKE CREATE ON SCHEMA public FROM PUBLIC;
    REVOKE USAGE ON SCHEMA public FROM PUBLIC;

    GRANT CREATE ON SCHEMA public TO $CKAN_USER;
    GRANT USAGE ON SCHEMA public TO $CKAN_USER;

    -- take connect permissions from main db
    REVOKE CONNECT ON DATABASE $CKAN_DB FROM $DATASTORE_USER;

    -- grant select permissions for read-only user
    GRANT CONNECT ON DATABASE $DATASTORE_DB TO $DATASTORE_USER;

    -- grant access to current tables and views to read-only user
    GRANT SELECT ON ALL TABLES IN SCHEMA public TO $DATASTORE_USER;

    -- grant access to new tables and views by default
    ALTER DEFAULT PRIVILEGES FOR USER $CKAN_USER IN SCHEMA public
       GRANT SELECT ON TABLES TO $DATASTORE_USER;
EOF

    # Database configured
    touch $PGDATA/db_configured

    # Open PostgreSQL ports to other machines/containers
    # (only now, because other containers may connect before postgis templates creation otherwise)
    echo "host    all    all          samenet    password" >> $PGMAIN/pg_hba.conf
    # Reload the configuration (by calling pg_reload_conf(); )
    setuser postgres psql -c "SELECT pg_reload_conf();"
  }
else
  init_db () {
    echo "CKAN database & datastore already configured"
  }
fi

init_db_when_ready () {
  # calls init_db when postgres is running
  while [[ ! -e /run/postgresql/9.3-main.pid ]]; do
      inotifywait -q -e create /run/postgresql/ >> /dev/null
  done

  init_db
}

if [[ ! -d "$PGDATA" ]]; then
  echo "Creating Postgres Directory..."
  # create dirs if needed
  mkdir -p $PGDATA
  # Ensure postgres owns the PGDATA
  chown -R postgres $PGDATA
  # Ensure we have the right permissions set on the PGDATA
  chmod -R 700 $PGDATA
fi

# initialize db if needed
if [[ ! "$(ls -A $PGDATA)" ]]; then
  echo "Initializing PostgreSQL..."
  chown -R postgres $PGDATA
  # postgres initdb
  #setuser postgres /usr/lib/postgresql/9.3/bin/initdb --locale=en_US.UTF-8 --encoding=UNICODE $PGDATA
  setuser postgres /usr/bin/initdb --locale=en_US.UTF-8 --encoding=UNICODE $PGDATA

  mv $PGDATA/*.conf $PGMAIN/
  # Update postgresql.conf settings
  sed -i -e "s|^#listen_addresses =.*$|listen_addresses = '*'|" $PGMAIN/postgresql.conf
  #sed -i -e "s|^#data_directory =.*$|data_directory = '/var/lib/postgresql/9.3/main'|" $PGMAIN/postgresql.conf
  sed -i -e "s|^#data_directory =.*$|data_directory = '/var/lib/pgsql/data'|" $PGMAIN/postgresql.conf
  sed -i -e "s|^#hba_file =.*$|hba_file = '/etc/postgresql/9.3/main/pg_hba.conf'|" $PGMAIN/postgresql.conf
  sed -i -e "s|^#ident_file =.*$|ident_file = '/etc/postgresql/9.3/main/pg_ident.conf'|" $PGMAIN/postgresql.conf
  sed -i -e "s|^#external_pid_file =.*$|external_pid_file = '/var/run/postgresql/9.3-main.pid'|" $PGMAIN/postgresql.conf
  # Allow connections from anywhere with valid credentials (md5)
  echo "local   all    postgres            peer" >> $PGMAIN/pg_hba.conf
  #echo "host    all    all          0.0.0.0/0    md5" >> $PGMAIN/pg_hba.conf
fi

init_db_when_ready &

# Start PostgreSQL
echo "Starting PostgreSQL..."
#setuser postgres /usr/lib/postgresql/9.3/bin/postgres -D $PGDATA -c config_file=$PGMAIN/postgresql.conf
setuser postgres /usr/bin/postgres -D $PGDATA -c config_file=$PGMAIN/postgresql.conf
